### PR TITLE
CygWin compatibility changes

### PR DESCRIPTION
**Pull request by djones60**
These changes make version 1.2 compatible with CygWin.  Some of my previous problems were corrected in Version 1.2.  Some others were dumb errors/misunderstanding of mine.

### CODE REVIEW

**Comment by djones60** [comment]
Forgot to mention.  This works in CygWin for both network and local files.

**Comment by thorpej** [comment]
This has been resolved in a slightly different way.  Please try out 1.2.1!

**Comment by djones60** [comment]
Great.  I've been looking at the changes you've been making with your branch leading up to 1.2.1.  I'll give it a try when I get a chance.

**Comment by djones60** [comment]
I just got a chance to try it.  Version 1.2.1 was able to do a configure and make with no problems.  When I tried running it, I got the error below.  The config file used is the same one from earlier testing and I gave it the same parameters are before.


D:\c\nabud>nabud -f -c nabud.conf
INFO: main: Welcome to NABU! I'm version 1.2.1 of your host, nabud.
INFO: main: Running as UID 197614, file creation mask 022
INFO: control_init: Creating control channel at /tmp/nabuctl.sock
ERROR: control_init: Unable to bind socket at /tmp/nabuctl.sock: No such file or directory
ERROR: fileio_load_file: Unable to read nabud.conf
ERROR: config_load: Unable to load configuration file.
ERROR: main: No connections! So boring! Goodbye.

D:\c\nabud>

**Pull request closed without merging**
