### PR TITLE
CygWin compatibility

### PR DESCRIPTION
**Pull request by djones60**
This is still a bit hacky.  But it allows this to compile under CygWin and server local files to the Nabu.  Feel free to reject it, clean it up, etc.  Sure won't mind.

### CODE REVIEW

**Comment by thorpej** [comment]
@djones60 Can you please attach the output of running "./configure"?

**Comment by djones60** [comment]
/* config.h.  Generated from config.h.in by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have <CommonCrypto/CommonCrypto.h> */
/* #undef HAVE_COMMONCRYPTO_H */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the `getprogname' function. */
#define HAVE_GETPROGNAME 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have OpenSSL. */
#define HAVE_OPENSSL 1

/* Define if you have POSIX threads libraries and header files. */
#define HAVE_PTHREAD 1

/* Have PTHREAD_PRIO_INHERIT. */
/* #undef HAVE_PTHREAD_PRIO_INHERIT */

/* Define to 1 if you have <Security/SecureTransport.h> */
/* #undef HAVE_SECURETRANSPORT */

/* Define if the struct sockaddr_un has a member sun_len on your OS */
/* #undef HAVE_SOCKADDR_UN_SUN_LEN */

/* Define if the struct stat has a member st_birthtime on your OS */
#define HAVE_STAT_ST_BIRTHTIME 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define if <sys/socket.h> has struct sockpeercred */
/* #undef HAVE_STRUCT_SOCKPEERCRED */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/ucred.h> header file. */
/* #undef HAVE_SYS_UCRED_H */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define if the struct xucred has a member cr_pid on your OS */
/* #undef HAVE_XUCRED_CR_PID */

/* Define to the sub-directory where libtool stores uninstalled libraries. */
#define LT_OBJDIR ".libs/"

/* Name of package */
#define PACKAGE "nabud-1.1"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "Jason Thorpe <thorpej@me.com>"

/* Define to the full name of this package. */
#define PACKAGE_NAME "nabud"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "nabud 1.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "nabud-1.1"

/* Define to the home page for this package. */
#define PACKAGE_URL "https://github.com/thorpej/nabud"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.1"

/* Define to necessary symbol if this constant uses a non-standard name on
   your system. */
/* #undef PTHREAD_CREATE_JOINABLE */

/* Define to 1 if all of the C90 standard headers exist (not just the ones
   required in a freestanding environment). This macro is provided for
   backward compatibility; new code need not use it. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.1"

**Comment by thorpej** [comment]
Oops, sorry, I meant the output of what ./configure prints to the terminal.

**Comment by djones60** [comment]
I think this is what you are needing :) 

$ ./configure
checking build system type... x86_64-pc-cygwin
checking host system type... x86_64-pc-cygwin
checking target system type... x86_64-pc-cygwin
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/x86_64-pc-cygwin/bin/ld.exe
checking if the linker (/usr/x86_64-pc-cygwin/bin/ld.exe) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 8192
checking how to convert x86_64-pc-cygwin file names to x86_64-pc-cygwin format... func_convert_file_noop
checking how to convert x86_64-pc-cygwin file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-pc-cygwin/bin/ld.exe option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for dlltool... dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/x86_64-pc-cygwin/bin/ld.exe) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking if using gcc... yes; adding to CFLAGS: "-Werror -Wall -Wstrict-prototypes -Wmissing-prototypes                      -Wpointer-arith -Wno-sign-compare -Wreturn-type -Wswitch                -Wshadow -Wcast-qual -Wwrite-strings           -Wformat=2 -Wno-format-zero-length"
checking for inttypes.h... (cached) yes
checking for sys/ucred.h... no
checking for CommonCrypto/CommonCrypto.h... no
checking for Security/SecureTransport.h... no
checking for pkg-config... pkg-config
checking whether compiling and linking against OpenSSL works... yes
checking how to run the C preprocessor... gcc -E
checking whether gcc is Clang... no
checking whether pthreads work with "-pthread" and "-lpthread"... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... no
checking for sun_len member in struct sockaddr_un... no
checking for cr_pid member in struct xucred... no
checking for struct sockpeercred in <sys/socket.h>... no
checking for st_birthtime member in struct stat... yes
checking for readline in -ledit... no
checking for readline in -lreadline... no
checking for getprogname... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating examples/Makefile
config.status: creating extras/darwin/launchd/Makefile
config.status: creating extras/freebsd/rc.conf.d/Makefile
config.status: creating extras/freebsd/rc.d/Makefile
config.status: creating extras/linux/systemd/Makefile
config.status: creating extras/netbsd/rc.conf.d/Makefile
config.status: creating extras/netbsd/rc.d/Makefile
config.status: creating extras/openbsd/rc.d/Makefile
config.status: creating libfetch/Makefile
config.status: creating libmj/Makefile
config.status: creating libnabud/Makefile
config.status: creating nabud/Makefile
config.status: creating nabuclient/Makefile
config.status: creating nabuctl/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure:  === Configuration results ===
configure: Version:                  1.2
configure: Installation prefix:      /usr/local
configure: Extras:
configure: C compiler:               gcc
configure: POSIX threads C compiler: gcc
configure: POSIX threads CFLAGS:     -pthread
configure: POSIX threads libraries:  -lpthread
configure: Warning CFLAGS:           -Werror -Wall -Wstrict-prototypes -Wmissing-prototypes                  -Wpointer-arith -Wno-sign-compare -Wreturn-type -Wswitch                -Wshadow -Wcast-qual -Wwrite-strings                    -Wformat=2 -Wno-format-zero-length -Wno-deprecated-declarations
configure: SSL support:              OpenSSL
configure: SSL includes:
configure: SSL libraries:            -lssl -lcrypto
configure: SSL LDFLAGS:
configure: PAK file support:         OpenSSL
configure: PAK file includes:
configure: PAK file libraries:       -lcrypto
configure: PAK file LDFLAGS:
configure: CLI includes:
configure: CLI libraries:
configure: =============================

Dave@davepc /cygdrive/d/c1/nabud-main
$

**Comment by djones60** [comment]
Ok.  Looks like my fork was a little stale.  Working on fixing things.

**Comment by djones60** [comment]
Hmm it looks like there are breaking changes in conn.c.  So this will take a while to figure out.  I am now getting ACK error messages when running nabud and trying to send a file.  The good thing is this was the same error I was getting when trying to server files from the internet.  So it sounds like it is a common problem.

**Comment by thorpej** [comment]
You probably need to make sure that the appropriate binary / text flags are set when opening things.  This is a common pitfall when using these Unix APIs on Windows.

**Comment by djones60** [comment]
The merge conflicts in conn.c is proving troublesome.  So going to close it.  Then do a new merge with the 1.3 changes.  Hopefully I can also figure out the TCP problem while I am at it.

**Comment by djones60** [comment]
Yep, completely forgot about those binary / text flags.  Show's it's been a whole since I much in C :)

**Pull request closed without merging**
